services:
  ns-setup:
    image: alpine:3.20
    container_name: ns-setup
    command: sh /scripts/setup.sh
    volumes:
      - ./data:/temp
      - ./mods:/mods
      - ./scripts/setup.sh:/scripts/setup.sh:ro
    restart: "no"
    networks:
      - ns-network

  ns-server:
    image: jives/hlds:valve
    container_name: ns-server
    environment:
      - GAME=ns
    volumes:
      - ./data:/temp
      - ./config/server.cfg:/temp/mods/ns/server.cfg:ro
      - ./config/mapcycle.txt:/temp/mods/ns/mapcycle.txt:ro
      - ./config/motd.txt:/temp/mods/ns/motd.txt:ro
    ports:
      - "27015:27015/udp"
      - "27015:27015"
      - "26900:26900/udp"
    command: >
      +log on
      +maxplayers 16
      +map ns_eclipse
      +exec server.cfg
    restart: unless-stopped
    networks:
      - ns-network

networks:
  ns-network:
    driver: bridge
