services:
  ns-setup:
    image: alpine:3.20
    container_name: ns-setup
    command: sh /scripts/setup.sh
    volumes:
      - ./data:/temp
      - ./scripts/setup.sh:/scripts/setup.sh:ro
    restart: "no"
    networks:
      - ns-network

  ns-server:
    image: jives/hlds:valve
    container_name: ns-server
    environment:
      - GAME=ns
    volumes:
      - ./data:/temp
      - ./logs:/opt/hlds/logs
      - ./config/server.cfg:/temp/mods/ns/server.cfg:ro
      - ./config/mapcycle.txt:/temp/mods/ns/mapcycle.txt:ro
      - ./config/motd.txt:/temp/mods/ns/motd.txt:ro
      - ./config/users.ini:/temp/mods/ns/addons/amxmodx/configs/users.ini:ro
      - ./config/plugins.ini:/temp/mods/ns/addons/amxmodx/configs/plugins.ini:ro
      - ./config/amxx.cfg:/temp/mods/ns/addons/amxmodx/configs/amxx.cfg:ro
    ports:
      - "27015:27015/udp"
      - "27015:27015"
      - "26900:26900/udp"
    command: >
      +log on
      +maxplayers 16
      +map ns_eclipse
      +sv_lan 0
      +exec server.cfg
    restart: unless-stopped
    networks:
      - ns-network
    depends_on:
      ns-setup:
        condition: service_completed_successfully

networks:
  ns-network:
    driver: bridge
